name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - name: Dependencies
        run: |
          npm install
          npm run package

      - name: Test (Ubuntu)
        run: xvfb-run npm test

      - name: Package
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'
