name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - name: Dependencies
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Test
        run: xvfb-run npm test

      - name: Package
        run: |
          npm run package
          vsce package

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: '*.vsix'

      - name: Prepare GitHub Pages artifact
        run: |
          mkdir gh-pages-artifact
          cp index.html gh-pages-artifact/
          cp -r libs gh-pages-artifact/
          cp -r media gh-pages-artifact/

      - name: Update GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages-artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
